language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - travis_retry composer install --no-progress --prefer-dist

script: $TRAVIS_BUILD_DIR/vendor/bin/phpunit --bootstrap $TRAVIS_BUILD_DIR/vendor/autoload.php $TRAVIS_BUILD_DIR/tests/
