language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'

install:
  - travis_retry composer install --no-progress --prefer-dist

script: $TRAVIS_BUILD_DIR/vendor/bin/phpunit --bootstrap $TRAVIS_BUILD_DIR/vendor/autoload.php $TRAVIS_BUILD_DIR/tests/
